-- ========================================================
-- MediCare Supabase (PostgreSQL) Schema Definition
-- Project URL: https://legcvukgzcyomlapjase.supabase.co
-- ========================================================

-- Enable UUID extension if needed
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- --------------------------------------------------------
-- 1. Users Table
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uid VARCHAR(64) UNIQUE NOT NULL,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(32),
    role VARCHAR(32) NOT NULL DEFAULT 'ROLE_PATIENT',
    dob VARCHAR(32),
    blood_group VARCHAR(10),
    address TEXT,
    emergency_contact VARCHAR(64),
    account_status VARCHAR(32) NOT NULL DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- --------------------------------------------------------
-- 2. Doctors Table
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_uid VARCHAR(64) UNIQUE NOT NULL,
    user_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL,
    phone VARCHAR(32),
    specialization VARCHAR(80) NOT NULL,
    experience VARCHAR(40),
    experience_years INT DEFAULT 5,
    rating NUMERIC(3, 1) DEFAULT 5.0,
    reviews_count INT DEFAULT 0,
    qualification VARCHAR(150),
    hospital VARCHAR(150),
    consultation_fee NUMERIC(10, 2) NOT NULL DEFAULT 50.00,
    is_available BOOLEAN DEFAULT TRUE,
    verification_status VARCHAR(32) NOT NULL DEFAULT 'Verified',
    account_status VARCHAR(32) NOT NULL DEFAULT 'Active',
    consultation_type VARCHAR(64) DEFAULT 'Online & In-Person',
    image TEXT,
    about TEXT,
    location TEXT,
    available_days JSONB DEFAULT '[]'::jsonb,
    available_time_slots JSONB DEFAULT '[]'::jsonb,
    languages JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- --------------------------------------------------------
-- 3. Appointments Table
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_uid VARCHAR(64) UNIQUE NOT NULL,
    patient_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
    patient_name VARCHAR(120) NOT NULL,
    patient_email VARCHAR(120) NOT NULL,
    patient_phone VARCHAR(32),
    doctor_id BIGINT REFERENCES public.doctors(id) ON DELETE SET NULL,
    doctor_uid VARCHAR(64) NOT NULL,
    doctor_name VARCHAR(120) NOT NULL,
    specialization VARCHAR(80) NOT NULL,
    appointment_date VARCHAR(32) NOT NULL,
    appointment_time VARCHAR(32) NOT NULL,
    reason TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'Pending',
    fee VARCHAR(32) DEFAULT '$50',
    consultation_type VARCHAR(64) DEFAULT 'In-Person',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- --------------------------------------------------------
-- 4. Activities Log Table
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_type VARCHAR(64) NOT NULL,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- --------------------------------------------------------
-- 5. Performance Indexes
-- --------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_user_uid ON public.users(user_uid);
CREATE INDEX IF NOT EXISTS idx_doctors_doctor_uid ON public.doctors(doctor_uid);
CREATE INDEX IF NOT EXISTS idx_doctors_specialization ON public.doctors(specialization);
CREATE INDEX IF NOT EXISTS idx_appointments_patient_id ON public.appointments(patient_id);
CREATE INDEX IF NOT EXISTS idx_appointments_doctor_id ON public.appointments(doctor_id);
CREATE INDEX IF NOT EXISTS idx_appointments_appointment_uid ON public.appointments(appointment_uid);

-- --------------------------------------------------------
-- 6. Row Level Security (RLS) & Permissions
-- --------------------------------------------------------
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;

-- Grant API access to anon and authenticated roles
GRANT ALL ON TABLE public.users TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.doctors TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.appointments TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.activities TO anon, authenticated, service_role;

GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Policies: Allow reading doctors publicly
CREATE POLICY "Allow public read on doctors"
    ON public.doctors FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Allow full access on doctors to authenticated"
    ON public.doctors FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Policies: Users
CREATE POLICY "Allow anon insert user during registration"
    ON public.users FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

CREATE POLICY "Allow users to read their profile"
    ON public.users FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Allow users to update profile"
    ON public.users FOR UPDATE
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- Policies: Appointments
CREATE POLICY "Allow public/patients to book appointment"
    ON public.appointments FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

CREATE POLICY "Allow read appointments"
    ON public.appointments FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Allow update appointments"
    ON public.appointments FOR UPDATE
    TO anon, authenticated
    USING (true)
    WITH CHECK (true);

-- Policies: Activities
CREATE POLICY "Allow read activities"
    ON public.activities FOR SELECT
    TO anon, authenticated
    USING (true);

CREATE POLICY "Allow insert activities"
    ON public.activities FOR INSERT
    TO anon, authenticated
    WITH CHECK (true);

-- --------------------------------------------------------
-- 7. Seed Initial Doctors
-- --------------------------------------------------------
INSERT INTO public.doctors (
    doctor_uid, name, email, phone, specialization, experience, experience_years, 
    rating, reviews_count, qualification, hospital, consultation_fee, is_available, 
    verification_status, account_status, consultation_type, image, about, location, 
    available_days, available_time_slots, languages
) VALUES 
(
    'doc-1',
    'Dr. Sarah Mitchell',
    'doctor@medicare.com',
    '+1 (555) 432-8765',
    'Cardiologist',
    '12+ Years',
    12,
    4.9,
    128,
    'MD, FACC - Harvard Medical School',
    'City Heart Institute & Wellness Center',
    75.00,
    true,
    'Verified',
    'Active',
    'Online & In-Person',
    'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=600',
    'Dr. Sarah Mitchell is a senior board-certified cardiologist with over a decade of clinical experience in preventive cardiology, cardiovascular disease management, and heart health diagnostics.',
    'Metro Medical Center, 4th Floor, Suite 402',
    '["Monday", "Wednesday", "Friday"]'::jsonb,
    '["09:00 AM", "10:30 AM", "02:00 PM", "04:30 PM"]'::jsonb,
    '["English", "Spanish"]'::jsonb
),
(
    'doc-2',
    'Dr. Alexander Chen',
    'alexander.chen@medicare.com',
    '+1 (555) 345-1234',
    'General Physician',
    '9+ Years',
    9,
    4.8,
    215,
    'MBBS, MD - Johns Hopkins University',
    'MediCare Central Family Clinic',
    50.00,
    true,
    'Verified',
    'Active',
    'Online & In-Person',
    'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=600',
    'Dr. Alexander Chen specializes in primary medical care, adult medicine, lifestyle disease management, and chronic illness monitoring with a compassionate patient-first philosophy.',
    'HealthCare Plaza, Building A',
    '["Monday", "Tuesday", "Thursday", "Saturday"]'::jsonb,
    '["08:30 AM", "11:00 AM", "01:30 PM", "03:30 PM"]'::jsonb,
    '["English", "Mandarin"]'::jsonb
),
(
    'doc-3',
    'Dr. Elena Rostova',
    'elena.rostova@medicare.com',
    '+1 (555) 567-8901',
    'Dermatologist',
    '8+ Years',
    8,
    4.9,
    164,
    'MD (Dermatology) - Stanford Medicine',
    'Aura Skin & Aesthetic Clinic',
    65.00,
    true,
    'Verified',
    'Active',
    'Online & In-Person',
    'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&q=80&w=600',
    'Dr. Elena Rostova is an acclaimed dermatologist specializing in clinical dermatology, acne treatments, eczema therapies, and non-invasive cosmetic skin restoration.',
    'Downtown Medical Suites, Floor 2',
    '["Tuesday", "Wednesday", "Saturday"]'::jsonb,
    '["10:00 AM", "12:00 PM", "03:00 PM", "05:00 PM"]'::jsonb,
    '["English", "Russian", "French"]'::jsonb
),
(
    'doc-4',
    'Dr. Marcus Johnson',
    'marcus.johnson@medicare.com',
    '+1 (555) 678-2345',
    'Orthopedic',
    '15+ Years',
    15,
    4.7,
    190,
    'MS (Orthopedics), FRCS - Oxford University',
    'Apex Joint & Sports Injury Pavilion',
    85.00,
    true,
    'Verified',
    'Active',
    'In-Person Only',
    'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=600',
    'Dr. Marcus Johnson brings over 15 years of orthopedic surgical and rehabilitation expertise, focusing on joint replacement, sports injury recovery, and spinal wellness.',
    'Apex Medical Tower, Room 510',
    '["Monday", "Wednesday", "Thursday"]'::jsonb,
    '["09:30 AM", "11:30 AM", "02:30 PM", "04:00 PM"]'::jsonb,
    '["English"]'::jsonb
),
(
    'doc-5',
    'Dr. Priya Patel',
    'priya.patel@medicare.com',
    '+1 (555) 789-3456',
    'Pediatrician',
    '11+ Years',
    11,
    5.0,
    310,
    'MD, DNB (Pediatrics) - Columbia University',
    'Little Smiles Children Hospital',
    55.00,
    true,
    'Verified',
    'Active',
    'Online & In-Person',
    'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=600',
    'Dr. Priya Patel is a dedicated pediatrician devoted to newborn care, child development milestones, vaccinations, and adolescent healthcare with a warm, kid-friendly demeanor.',
    'Children’s Health Hub, Suite 101',
    '["Tuesday", "Thursday", "Friday", "Saturday"]'::jsonb,
    '["09:00 AM", "10:00 AM", "01:00 PM", "03:00 PM"]'::jsonb,
    '["English", "Hindi", "Gujarati"]'::jsonb
),
(
    'doc-6',
    'Dr. David Sterling',
    'david.sterling@medicare.com',
    '+1 (555) 890-4567',
    'Neurologist',
    '14+ Years',
    14,
    4.8,
    98,
    'MD, PhD (Neurology) - Yale School of Medicine',
    'NeuroScience Care & Research Center',
    95.00,
    false,
    'Verified',
    'Active',
    'In-Person Only',
    'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&q=80&w=600',
    'Dr. David Sterling is a consultant neurologist specializing in migraines, neurological disorders, cognitive health, stroke rehabilitation, and comprehensive brain imaging assessments.',
    'Neurological Institute, 3rd Floor',
    '["Monday", "Tuesday", "Friday"]'::jsonb,
    '["11:00 AM", "01:00 PM", "04:00 PM"]'::jsonb,
    '["English", "German"]'::jsonb
)
ON CONFLICT (doctor_uid) DO NOTHING;
